#ifndef STRUCTURES_H
#define STRUCTURES_H

#include "protocol/structures/buttoncapabilities.h"
#include "protocol/structures/presetbankcapabilities.h"
#include "protocol/structures/ttschunk.h"
#include "protocol/structures/image.h"
#include "protocol/structures/textfieldstruct.h"
#include "protocol/structures/softbutton.h"
#include "protocol/structures/turn.h"
#include "protocol/structures/deviceinfo.h"
#include "protocol/structures/hmiapplication.h"
#include "protocol/structures/menuparams.h"
#include "protocol/structures/choice.h"
#include "protocol/structures/vrhelpitem.h"
#include "protocol/structures/timeformat.h"
#include "protocol/structures/keyboardproperties.h"
#include "protocol/structures/textfield.h"
#include "protocol/structures/imageresolution.h"
#include "protocol/structures/imagefield.h"
#include "protocol/structures/toucheventcapabilities.h"
#include "protocol/structures/screenparams.h"
#include "protocol/structures/displaycapabilities.h"
#include "protocol/structures/audiopassthrucapabilities.h"
#include "protocol/structures/softbuttoncapabilities.h"
#include "protocol/structures/hmicapabilities.h"
#include "protocol/structures/touchcoord.h"
#include "protocol/structures/touchevent.h"

#endif // STRUCTURES_H
